### ISSUE TITLE
Unable to capture touch_state_data after CuEVM execution

### ISSUE THREAD

**Issue by lnteng** [sbip-sg/CuEVM#38]
Hello!

I want to see the [results](https://github.com/sbip-sg/CuEVM/blob/main/interpreter/interpreter.cu#L22-L32) produced after the execution of CuEVM on the main branch. However, I can only output the `world_state_data `and the `transaction`, while the `touch_state_data` remains empty.

**Comment by minhhn2910** [comment]
Hi, currently the touch state at that location (line 28)  is pre-execution. If you want to print it, you can try to print at line 42 in that code. 

Please note that currently we do not output the state dump similar to geth yet, and printing state to stdout is not recommended as it will slow down the execution significantly. 

For input and output state and interacting with CuEVM, we recommend you to use the library mode in python at the moment (only binary available, we will update the source soon): 
* [Github Repo](https://github.com/minhhn2910/DemoLibCuEVM) 
* [Google Colab](https://colab.research.google.com/drive/1xPvjpALzXGxCWgvdBs-HiynE0XKytcb4?usp=sharing)

**Comment by lnteng** [comment]
Thank you for your response. I tried again and successfully achieved the desired result. This is a very meaningful project, and I look forward to your future updates.
